function c_to_ri_init_xblock(n_bits, bin_pt)
%% inports
c = xInport('c');

%% outports
re = xOutport('re');
im = xOutport('im');

%% diagram

% block: untitled1/c_to_ri/force_im
slice_im_out1 = xSignal;
force_im = xBlock(struct('source', 'Reinterpret', 'name', 'force_im'), ...
                         struct('force_arith_type', 'on', ...
                                'arith_type', 'Signed  (2''s comp)', ...
                                'force_bin_pt', 'on', ...
                                'bin_pt', bin_pt), ...
                         {slice_im_out1}, ...
                         {im});

% block: untitled1/c_to_ri/force_re
slice_re_out1 = xSignal;
force_re = xBlock(struct('source', 'Reinterpret', 'name', 'force_re'), ...
                         struct('force_arith_type', 'on', ...
                                'arith_type', 'Signed  (2''s comp)', ...
                                'force_bin_pt', 'on', ...
                                'bin_pt', bin_pt), ...
                         {slice_re_out1}, ...
                         {re});

% block: untitled1/c_to_ri/slice_im
slice_im = xBlock(struct('source', 'Slice', 'name', 'slice_im'), ...
                         struct('nbits', n_bits, ...
                                'mode', 'Lower Bit Location + Width'), ...
                         {c}, ...
                         {slice_im_out1});

% block: untitled1/c_to_ri/slice_re
slice_re = xBlock(struct('source', 'Slice', 'name', 'slice_re'), ...
                         struct('nbits', n_bits), ...
                         {c}, ...
                         {slice_re_out1});



end

