function negate_mux(mux_latency, input_bit_width, input_bin_pt)

sel = xInport('sel');
b_re = xInport('b_re');
b_im = xInport('b_im');

%% outports
bw_im = xOutport('bw_im');

%% diagram

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/Convert
Convert_out1 = xSignal;
Convert = xBlock(struct('source', 'Convert', 'name', 'Convert'), ...
                        struct('n_bits', 18, ...
                               'bin_pt', 18 - (input_bit_width - input_bin_pt)), ...
                        {b_re}, ...
                        {Convert_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/Convert1
Reinterpret_out1 = xSignal;
Convert1 = xBlock(struct('source', 'Convert', 'name', 'Convert1'), ...
                         struct('n_bits', input_bit_width, ...
                                'bin_pt', input_bin_pt, ...
                                'overflow', 'Saturate', ...
                                'latency', mux_latency-1), ...
                         {Reinterpret_out1}, ...
                         {bw_im});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/Convert2
cin_delay_out1 = xSignal;
Convert2_out1 = xSignal;
Convert2 = xBlock(struct('source', 'Convert', 'name', 'Convert2'), ...
                         struct('n_bits', 48, ...
                                'bin_pt', 18 - (input_bit_width - input_bin_pt)), ...
                         {cin_delay_out1}, ...
                         {Convert2_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/DSP48E
negate_factor_out1 = xSignal;
Reinterpret1_out1 = xSignal;
Reinterpret2_out1 = xSignal;
mux2_out1 = xSignal;
alumode0_out1 = xSignal;
carryin0_out1 = xSignal;
carryinsel0_out1 = xSignal;
DSP48E_out1 = xSignal;
DSP48E = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E'), ...
                       struct('use_creg', 'on', ...
                              'pipeline_opmode', 'off'), ...
                       {negate_factor_out1, Reinterpret1_out1, Reinterpret2_out1, mux2_out1, alumode0_out1, carryin0_out1, carryinsel0_out1}, ...
                       {DSP48E_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/Reinterpret
Reinterpret = xBlock(struct('source', 'Reinterpret', 'name', 'Reinterpret'), ...
                            struct('force_arith_type', 'on', ...
                                   'arith_type', 'Signed  (2''s comp)', ...
                                   'force_bin_pt', 'on', ...
                                   'bin_pt', 18 - (input_bit_width-input_bin_pt)), ...
                            {DSP48E_out1}, ...
                            {Reinterpret_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/Reinterpret1
Reinterpret1 = xBlock(struct('source', 'Reinterpret', 'name', 'Reinterpret1'), ...
                             struct('force_arith_type', 'on', ...
                                    'arith_type', 'Signed  (2''s comp)', ...
                                    'force_bin_pt', 'on'), ...
                             {Convert_out1}, ...
                             {Reinterpret1_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/Reinterpret2
Reinterpret2 = xBlock(struct('source', 'Reinterpret', 'name', 'Reinterpret2'), ...
                             struct('force_arith_type', 'on', ...
                                    'arith_type', 'Signed  (2''s comp)', ...
                                    'force_bin_pt', 'on'), ...
                             {Convert2_out1}, ...
                             {Reinterpret2_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/alumode0
alumode0 = xBlock(struct('source', 'Constant', 'name', 'alumode0'), ...
                         struct('arith_type', 'Unsigned', ...
                                'const', 0, ...
                                'n_bits', 4, ...
                                'bin_pt', 0, ...
                                'explicit_period', 'on'), ...
                         {}, ...
                         {alumode0_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/carryin0
carryin0 = xBlock(struct('source', 'Constant', 'name', 'carryin0'), ...
                         struct('arith_type', 'Unsigned', ...
                                'const', 0, ...
                                'n_bits', 1, ...
                                'bin_pt', 0, ...
                                'explicit_period', 'on'), ...
                         {}, ...
                         {carryin0_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/carryinsel0
carryinsel0 = xBlock(struct('source', 'Constant', 'name', 'carryinsel0'), ...
                            struct('arith_type', 'Unsigned', ...
                                   'const', 0, ...
                                   'n_bits', 3, ...
                                   'bin_pt', 0, ...
                                   'explicit_period', 'on'), ...
                            {}, ...
                            {carryinsel0_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/cin_delay
cin_delay = xBlock(struct('source', 'Delay', 'name', 'cin_delay'), ...
                          struct('reg_retiming', 'on'), ...
                          {b_im}, ...
                          {cin_delay_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/mux2
opmode_b_re_out1 = xSignal;
opmode_negb_im_out1 = xSignal;
mux2 = xBlock(struct('source', 'Mux', 'name', 'mux2'), ...
                     [], ...
                     {sel, opmode_b_re_out1, opmode_negb_im_out1}, ...
                     {mux2_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/negate_factor
negate_factor = xBlock(struct('source', 'Constant', 'name', 'negate_factor'), ...
                              struct('const', -1, ...
                                     'n_bits', 30, ...
                                     'bin_pt', 0, ...
                                     'explicit_period', 'on'), ...
                              {}, ...
                              {negate_factor_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/opmode_b_re
opmode_b_re = xBlock(struct('source', 'Constant', 'name', 'opmode_b_re'), ...
                            struct('arith_type', 'Unsigned', ...
                                   'const', 12, ...
                                   'n_bits', 7, ...
                                   'bin_pt', 0, ...
                                   'explicit_period', 'on'), ...
                            {}, ...
                            {opmode_b_re_out1});

% block: twiddle_stage_2_test/twiddle_stage_1/negate_mux/opmode_negb_im
opmode_negb_im = xBlock(struct('source', 'Constant', 'name', 'opmode_negb_im'), ...
                               struct('arith_type', 'Unsigned', ...
                                      'const', 5, ...
                                      'n_bits', 7, ...
                                      'bin_pt', 0, ...
                                      'explicit_period', 'on'), ...
                               {}, ...
                               {opmode_negb_im_out1});



end

