function sync_delay_init_xblock(DelayLen)


% Mask Initialization code
BitWidth = max(2, ceil(log2(DelayLen+1)));
UseCounter = 1;
if DelayLen == 0,
	UseCounter = 0;
end

%% inports
xlsub2_In = xInport('In');

%% outports
xlsub2_Out = xOutport('Out');

%% diagram

% block: delay_7/sync_delay/Constant
xlsub2_Constant_out1 = xSignal;
xlsub2_Constant = xBlock(struct('source', 'Constant', 'name', 'Constant'), ...
                         struct('arith_type', 'Unsigned', ...
                                'n_bits', BitWidth, ...
                                'bin_pt', 0, ...
                                'explicit_period', 'on'), ...
                         {}, ...
                         {xlsub2_Constant_out1});

% block: delay_7/sync_delay/Constant1
xlsub2_Constant1_out1 = xSignal;
xlsub2_Constant1 = xBlock(struct('source', 'Constant', 'name', 'Constant1'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', BitWidth, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant1_out1});

% block: delay_7/sync_delay/Constant2
xlsub2_Constant2_out1 = xSignal;
xlsub2_Constant2 = xBlock(struct('source', 'Constant', 'name', 'Constant2'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', DelayLen, ...
                                 'n_bits', BitWidth, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant2_out1});

% block: delay_7/sync_delay/Constant3
xlsub2_Constant3_out1 = xSignal;
xlsub2_Constant3 = xBlock(struct('source', 'Constant', 'name', 'Constant3'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', UseCounter, ...
                                 'n_bits', 1, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant3_out1});

% block: delay_7/sync_delay/Counter
xlsub2_Logical_out1 = xSignal;
xlsub2_Counter_out1 = xSignal;
xlsub2_Counter = xBlock(struct('source', 'Counter', 'name', 'Counter'), ...
                        struct('operation', 'Down', ...
                               'n_bits', BitWidth, ...
                               'load_pin', 'on', ...
                               'en', 'on', ...
                               'use_rpm', 'on'), ...
                        {xlsub2_In, xlsub2_Constant2_out1, xlsub2_Logical_out1}, ...
                        {xlsub2_Counter_out1});

% block: delay_7/sync_delay/Logical
xlsub2_Relational1_out1 = xSignal;
xlsub2_Logical = xBlock(struct('source', 'Logical', 'name', 'Logical'), ...
                        struct('logical_function', 'OR', ...
                               'n_bits', 8, ...
                               'bin_pt', 2), ...
                        {xlsub2_In, xlsub2_Relational1_out1}, ...
                        {xlsub2_Logical_out1});

% block: delay_7/sync_delay/Mux
xlsub2_Relational_out1 = xSignal;
xlsub2_Mux = xBlock(struct('source', 'Mux', 'name', 'Mux'), ...
                    struct('arith_type', 'Signed  (2''s comp)', ...
                           'n_bits', 8, ...
                           'bin_pt', 2), ...
                    {xlsub2_Constant3_out1, xlsub2_In, xlsub2_Relational_out1}, ...
                    {xlsub2_Out});

% block: delay_7/sync_delay/Relational
xlsub2_Relational = xBlock(struct('source', 'Relational', 'name', 'Relational'), ...
                           struct('latency', 0), ...
                           {xlsub2_Constant_out1, xlsub2_Counter_out1}, ...
                           {xlsub2_Relational_out1});

% block: delay_7/sync_delay/Relational1
xlsub2_Relational1 = xBlock(struct('source', 'Relational', 'name', 'Relational1'), ...
                            struct('mode', 'a!=b', ...
                                   'latency', 0), ...
                            {xlsub2_Counter_out1, xlsub2_Constant1_out1}, ...
                            {xlsub2_Relational1_out1});

% block: delay_7/sync_delay/warn period Logical0
xlsub2_warn_period_Logical0 = xBlock(struct('source', 'xbsReplacements_r4/Warning', 'name', 'warn period Logical0'), ...
                                     struct('period', 1), ...
                                     {}, ...
                                     {});

% block: delay_7/sync_delay/warn period Relational10
xlsub2_warn_period_Relational10 = xBlock(struct('source', 'xbsReplacements_r4/Warning', 'name', 'warn period Relational10'), ...
                                         struct('period', 1), ...
                                         {}, ...
                                         {});



end

