function sync_delay_prog_init_xblock(MaxDelay)



%% inports
xlsub2_sync = xInport('sync');
xlsub2_delay = xInport('delay');

%% outports
xlsub2_sync_out = xOutport('sync_out');

%% diagram

% block: delay_7/sync_delay_prog/Constant
xlsub2_Constant_out1 = xSignal;
xlsub2_Constant = xBlock(struct('source', 'Constant', 'name', 'Constant'), ...
                         struct('arith_type', 'Unsigned', ...
                                'n_bits', MaxDelay, ...
                                'bin_pt', 0, ...
                                'explicit_period', 'on'), ...
                         {}, ...
                         {xlsub2_Constant_out1});

% block: delay_7/sync_delay_prog/Constant1
xlsub2_Constant1_out1 = xSignal;
xlsub2_Constant1 = xBlock(struct('source', 'Constant', 'name', 'Constant1'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', MaxDelay, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant1_out1});

% block: delay_7/sync_delay_prog/Counter
xlsub2_Logical_out1 = xSignal;
xlsub2_Counter_out1 = xSignal;
xlsub2_Counter = xBlock(struct('source', 'Counter', 'name', 'Counter'), ...
                        struct('operation', 'Down', ...
                               'n_bits', MaxDelay, ...
                               'load_pin', 'on', ...
                               'en', 'on', ...
                               'use_rpm', 'on'), ...
                        {xlsub2_sync, xlsub2_delay, xlsub2_Logical_out1}, ...
                        {xlsub2_Counter_out1});

% block: delay_7/sync_delay_prog/Logical
xlsub2_Relational1_out1 = xSignal;
xlsub2_Logical = xBlock(struct('source', 'Logical', 'name', 'Logical'), ...
                        struct('logical_function', 'OR', ...
                               'n_bits', 8, ...
                               'bin_pt', 2), ...
                        {xlsub2_sync, xlsub2_Relational1_out1}, ...
                        {xlsub2_Logical_out1});

% block: delay_7/sync_delay_prog/Relational
xlsub2_Relational = xBlock(struct('source', 'Relational', 'name', 'Relational'), ...
                           struct('latency', 0), ...
                           {xlsub2_Constant_out1, xlsub2_Counter_out1}, ...
                           {xlsub2_sync_out});

% block: delay_7/sync_delay_prog/Relational1
xlsub2_Relational1 = xBlock(struct('source', 'Relational', 'name', 'Relational1'), ...
                            struct('mode', 'a!=b', ...
                                   'latency', 0), ...
                            {xlsub2_Counter_out1, xlsub2_Constant1_out1}, ...
                            {xlsub2_Relational1_out1});



end

