function window_delay_init_xblock(delay)


%% inports
xlsub2_in = xInport('in');

%% outports
xlsub2_out = xOutport('out');

%% diagram

% block: delay_7/window_delay/Gateway Out2
xlsub2_sync_delay1_out1 = xSignal;
xlsub2_Gateway_Out2_out1 = xSignal;
xlsub2_Gateway_Out2 = xBlock(struct('source', 'Gateway Out', 'name', 'Gateway Out2'), ...
                             [], ...
                             {xlsub2_sync_delay1_out1}, ...
                             {xlsub2_Gateway_Out2_out1});

% block: delay_7/window_delay/Gateway Out3
xlsub2_Register_out1 = xSignal;
xlsub2_Gateway_Out3_out1 = xSignal;
xlsub2_Gateway_Out3 = xBlock(struct('source', 'Gateway Out', 'name', 'Gateway Out3'), ...
                             [], ...
                             {xlsub2_Register_out1}, ...
                             {xlsub2_Gateway_Out3_out1});

% block: delay_7/window_delay/Gateway Out55
xlsub2_Gateway_Out55_out1 = xSignal;
xlsub2_Gateway_Out55 = xBlock(struct('source', 'Gateway Out', 'name', 'Gateway Out55'), ...
                              [], ...
                              {xlsub2_in}, ...
                              {xlsub2_Gateway_Out55_out1});

% block: delay_7/window_delay/Gateway Out56
xlsub2_sync_delay_out1 = xSignal;
xlsub2_Gateway_Out56_out1 = xSignal;
xlsub2_Gateway_Out56 = xBlock(struct('source', 'Gateway Out', 'name', 'Gateway Out56'), ...
                              [], ...
                              {xlsub2_sync_delay_out1}, ...
                              {xlsub2_Gateway_Out56_out1});

% block: delay_7/window_delay/Register
xlsub2_Register = xBlock(struct('source', 'Register', 'name', 'Register'), ...
                         struct('rst', 'on', ...
                                'en', 'on'), ...
                         {xlsub2_sync_delay_out1, xlsub2_sync_delay1_out1, xlsub2_sync_delay_out1}, ...
                         {xlsub2_Register_out1});


% block: delay_7/window_delay/negedge
xlsub2_negedge_out1 = xSignal;
xlsub2_negedge = xBlock(struct('source', 'casper_library_misc/negedge', 'name', 'negedge'), ...
                        [], ...
                        {xlsub2_in}, ...
                        {xlsub2_negedge_out1});

% block: delay_7/window_delay/posedge3
xlsub2_posedge3_out1 = xSignal;
xlsub2_posedge3 = xBlock(struct('source', 'casper_library_misc/posedge', 'name', 'posedge3'), ...
                         [], ...
                         {xlsub2_in}, ...
                         {xlsub2_posedge3_out1});

% block: delay_7/window_delay/sync_delay
xlsub2_sync_delay = xBlock(struct('source', 'casper_library_delays/sync_delay', 'name', 'sync_delay'), ...
                           struct('DelayLen', delay-1), ...
                           {xlsub2_posedge3_out1}, ...
                           {xlsub2_sync_delay_out1});

% block: delay_7/window_delay/sync_delay1
xlsub2_sync_delay1 = xBlock(struct('source', 'casper_library_delays/sync_delay', 'name', 'sync_delay1'), ...
                            struct('DelayLen', delay-1), ...
                            {xlsub2_negedge_out1}, ...
                            {xlsub2_sync_delay1_out1});

% extra outport assignment
xlsub2_out.assign(xlsub2_Register_out1);


end

