%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                             %
%   Center for Astronomy Signal Processing and Electronics Research           %
%   http://casper.berkeley.edu                                                %      
%   Copyright (C) 2011 Hong Chen                                              %
%                                                                             %
%   This program is free software; you can redistribute it and/or modify      %
%   it under the terms of the GNU General Public License as published by      %
%   the Free Software Foundation; either version 2 of the License, or         %
%   (at your option) any later version.                                       %
%                                                                             %
%   This program is distributed in the hope that it will be useful,           %
%   but WITHOUT ANY WARRANTY; without even the implied warranty of            %
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             %
%   GNU General Public License for more details.                              %
%                                                                             %
%   You should have received a copy of the GNU General Public License along   %
%   with this program; if not, write to the Free Software Foundation, Inc.,   %
%   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.               %
%                                                                             %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function hilbert_dsp48e_init_xblock(blk, BitWidth, conv_latency)


%% inports
xlsub2_a = xInport('a');
xlsub2_b = xInport('b');

%% outports
xlsub2_even = xOutport('even');
xlsub2_odd = xOutport('odd');

%% diagram

% block: untitled/hilbert_dsp48e/Convert0
xlsub2_Scale0_out1 = xSignal;
xlsub2_Convert0_out1 = xSignal;
xlsub2_Convert0 = xBlock(struct('source', 'Convert', 'name', 'Convert0'), ...
                         struct('n_bits', BitWidth, ...
                                'bin_pt', BitWidth - 1, ...
                                'quantization', 'Round  (unbiased: Even Values)', ...
                                'latency', conv_latency, ...
                                'pipeline', 'on'), ...
                         {xlsub2_Scale0_out1}, ...
                         {xlsub2_Convert0_out1});

% block: untitled/hilbert_dsp48e/Convert1
xlsub2_Scale1_out1 = xSignal;
xlsub2_Convert1_out1 = xSignal;
xlsub2_Convert1 = xBlock(struct('source', 'Convert', 'name', 'Convert1'), ...
                         struct('n_bits', BitWidth, ...
                                'bin_pt', BitWidth - 1, ...
                                'quantization', 'Round  (unbiased: Even Values)', ...
                                'latency', conv_latency, ...
                                'pipeline', 'on'), ...
                         {xlsub2_Scale1_out1}, ...
                         {xlsub2_Convert1_out1});

% block: untitled/hilbert_dsp48e/Convert2
xlsub2_Scale2_out1 = xSignal;
xlsub2_Convert2_out1 = xSignal;
xlsub2_Convert2 = xBlock(struct('source', 'Convert', 'name', 'Convert2'), ...
                         struct('n_bits', BitWidth, ...
                                'bin_pt', BitWidth - 1, ...
                                'quantization', 'Round  (unbiased: Even Values)', ...
                                'latency', conv_latency, ...
                                'pipeline', 'on'), ...
                         {xlsub2_Scale2_out1}, ...
                         {xlsub2_Convert2_out1});

% block: untitled/hilbert_dsp48e/Convert3
xlsub2_Scale3_out1 = xSignal;
xlsub2_Convert3_out1 = xSignal;
xlsub2_Convert3 = xBlock(struct('source', 'Convert', 'name', 'Convert3'), ...
                         struct('n_bits', BitWidth, ...
                                'bin_pt', BitWidth - 1, ...
                                'quantization', 'Round  (unbiased: Even Values)', ...
                                'latency', conv_latency, ...
                                'pipeline', 'on'), ...
                         {xlsub2_Scale3_out1}, ...
                         {xlsub2_Convert3_out1});

% block: untitled/hilbert_dsp48e/Scale0
xlsub2_cadd_out1 = xSignal;
xlsub2_Scale0 = xBlock(struct('source', 'Scale', 'name', 'Scale0'), ...
                       struct('scale_factor', -1), ...
                       {xlsub2_cadd_out1}, ...
                       {xlsub2_Scale0_out1});

% block: untitled/hilbert_dsp48e/Scale1
xlsub2_cadd_out2 = xSignal;
xlsub2_Scale1 = xBlock(struct('source', 'Scale', 'name', 'Scale1'), ...
                       struct('scale_factor', -1), ...
                       {xlsub2_cadd_out2}, ...
                       {xlsub2_Scale1_out1});

% block: untitled/hilbert_dsp48e/Scale2
xlsub2_csub_out1 = xSignal;
xlsub2_Scale2 = xBlock(struct('source', 'Scale', 'name', 'Scale2'), ...
                       struct('scale_factor', -1), ...
                       {xlsub2_csub_out1}, ...
                       {xlsub2_Scale2_out1});

% block: untitled/hilbert_dsp48e/Scale3
xlsub2_csub_out2 = xSignal;
xlsub2_Scale3 = xBlock(struct('source', 'Scale', 'name', 'Scale3'), ...
                       struct('scale_factor', -1), ...
                       {xlsub2_csub_out2}, ...
                       {xlsub2_Scale3_out1});

% block: untitled/hilbert_dsp48e/c_to_ri0
xlsub2_c_to_ri0_out1 = xSignal;
xlsub2_c_to_ri0_out2 = xSignal;
xlsub2_c_to_ri0_sub = xBlock(struct('source', str2func('c_to_ri_init_xblock'), 'name', 'c_to_ri0'), ...
                         {[blk, '/c_to_ri0'],BitWidth, BitWidth-1}, ...
                         {xlsub2_a}, ...
                         {xlsub2_c_to_ri0_out1, xlsub2_c_to_ri0_out2});

% block: untitled/hilbert_dsp48e/c_to_ri1
xlsub2_c_to_ri1_out1 = xSignal;
xlsub2_c_to_ri1_out2 = xSignal;
xlsub2_c_to_ri1_sub = xBlock(struct('source', str2func('c_to_ri_init_xblock'), 'name', 'c_to_ri1'), ...
                         {[blk, '/c_to_ri1'],BitWidth, BitWidth-1}, ...
                         {xlsub2_b}, ...
                         {xlsub2_c_to_ri1_out1, xlsub2_c_to_ri1_out2});

% block: untitled/hilbert_dsp48e/cadd
xlsub2_cadd_sub = xBlock(struct('source', str2func('simd_add_dsp48e_init_xblock'), 'name', 'cadd'), ...
                     {[blk, '/cadd'],'Addition', BitWidth, BitWidth - 1, BitWidth, BitWidth - 1, 'on', 19, 17, 'Truncate', 'Wrap', 0}, ...
                     {xlsub2_c_to_ri0_out1, xlsub2_c_to_ri0_out2, xlsub2_c_to_ri1_out1, xlsub2_c_to_ri1_out2}, ...
                     {xlsub2_cadd_out1, xlsub2_cadd_out2});

% block: untitled/hilbert_dsp48e/csub
xlsub2_csub_sub = xBlock(struct('source', str2func('simd_add_dsp48e_init_xblock'), 'name', 'csub'), ...
                     {[blk, '/csub'], 'Subtraction', BitWidth, BitWidth - 1, BitWidth, BitWidth - 1, 'on', 19, 17, 'Truncate', 'Wrap', 0}, ...
                     {xlsub2_c_to_ri0_out2, xlsub2_c_to_ri1_out1, xlsub2_c_to_ri1_out2, xlsub2_c_to_ri0_out1}, ...
                     {xlsub2_csub_out1, xlsub2_csub_out2});

% block: untitled/hilbert_dsp48e/ri_to_c0
xlsub2_ri_to_c0_sub = xBlock(struct('source', str2func('ri_to_c_init_xblock'), 'name', 'ri_to_c0'), ...
                         {}, ...
                         {xlsub2_Convert0_out1, xlsub2_Convert2_out1}, ...
                         {xlsub2_even});

% block: untitled/hilbert_dsp48e/ri_to_c1
xlsub2_ri_to_c1_sub = xBlock(struct('source', str2func('ri_to_c_init_xblock'), 'name', 'ri_to_c1'), ...
                         {}, ...
                         {xlsub2_Convert1_out1, xlsub2_Convert3_out1}, ...
                         {xlsub2_odd});



if ~isempty(blk) && ~strcmp(blk(1),'/')
    clean_blocks(blk);
end

end

