function sample_and_hold_init_xblock(blk, varargin)


defaults = {'period', 1024};
period = get_var('period', 'defaults', defaults, varargin{:});

sync = xInport('sync');
in = xInport('in');

out = xOutport('out');

en = xSignal('en');
hold_en = xBlock(struct('source', str2func('hold_en_init_xblock'), 'name', 'hold_en'), ...
            {[blk, '/hold_en'], ...
            'hold_period', period, ...
            'explicit_clk_rate', 'on', ...
            'input_clk_period', 1}, ...
        {sync}, ...
        {en});
    
Register = xBlock(struct('source', 'Register', 'name', 'Register'), ...
                             struct('en', 'on'), ...
                             {in, en}, ...
                             {out});

end