function clft = xblocks_library_forwarding_table
% Returns a forwarding table suitable for use with xblocks_library.mdl.
% 
% This script is intended to make it easier to rearrange the xblocks_library
% library.  "clft" is a cell array of two-element cell arrays, each of
% which specifies the old and new path of a block that has moved.
%
% To update the forwarding table of xblocks_library.mdl, simply run...
%
% set_param('xblocks_library';'ForwardingTable',xblocks_library_forwarding_table);
%
% ...which will completely overwrite the value of the ForwardingTable
% parameter of the xblocks_library library with the value returned by this
% function.
%
% Don't forget to unlock xblocks_library beforehand!
% Don't forget to save xblocks_library afterwards!

clft = ...
{ ...
{'xblocks_library/Accumulators/dram_vacc';'xblocks_library_accumulators/dram_vacc'}, ...
{'xblocks_library/Accumulators/qdr_vacc';'xblocks_library_accumulators/qdr_vacc'}, ...
{'xblocks_library/Accumulators/simple_bram_vacc';'xblocks_library_accumulators/simple_bram_vacc'}, ...
{'xblocks_library/Accumulators/vacc_tvg';'xblocks_library_accumulators/vacc_tvg'}, ...
{'xblocks_library/Communications/gbe_mux';'xblocks_library_communications/gbe_mux'}, ...
{'xblocks_library/Communications/pkt_buf';'xblocks_library_communications/pkt_buf'}, ...
{'xblocks_library/Correlator/auto_tap';'xblocks_library_correlator/auto_tap'}, ...
{'xblocks_library/Correlator/baseline_tap';'xblocks_library_correlator/baseline_tap'}, ...
{'xblocks_library/Correlator/cross_multiplier';'xblocks_library_correlator/cross_multiplier'}, ...
{'xblocks_library/Correlator/x_cast';'xblocks_library_correlator/x_cast'}, ...
{'xblocks_library/Correlator/xeng';'xblocks_library_correlator/xeng'}, ...
{'xblocks_library/Correlator/xeng_conj_fix';'xblocks_library_correlator/xeng_conj_fix'}, ...
{'xblocks_library/Correlator/xeng_descramble';'xblocks_library_correlator/xeng_descramble'}, ...
{'xblocks_library/Correlator/xeng_descramble_4ant';'xblocks_library_correlator/xeng_descramble_4ant'}, ...
{'xblocks_library/Correlator/xeng_tvg';'xblocks_library_correlator/xeng_tvg'}, ...
{'xblocks_library/Delays/Datatype_Conv_Cos';'xblocks_library_delays/Datatype_Conv_Cos'}, ...
{'xblocks_library/Delays/Datatype_Conv_Sine';'xblocks_library_delays/Datatype_Conv_Sine'}, ...
{'xblocks_library/Delays/Fine_del_sub_blk';'xblocks_library_delays/Fine_del_sub_blk'}, ...
{'xblocks_library/Delays/Fringe_sub_blk';'xblocks_library_delays/Fringe_sub_blk'}, ...
{'xblocks_library/Delays/delay_bram';'xblocks_library_delays/delay_bram'}, ...
{'xblocks_library/Delays/delay_bram_en_plus';'xblocks_library_delays/delay_bram_en_plus'}, ...
{'xblocks_library/Delays/delay_bram_prog';'xblocks_library_delays/delay_bram_prog'}, ...
{'xblocks_library/Delays/delay_bram_prog_dp';'xblocks_library_delays/delay_bram_prog_dp'}, ...
{'xblocks_library/Delays/delay_complex';'xblocks_library_delays/delay_complex'}, ...
{'xblocks_library/Delays/delay_slr';'xblocks_library_delays/delay_slr'}, ...
{'xblocks_library/Delays/delay_wideband_prog';'xblocks_library_delays/delay_wideband_prog'}, ...
{'xblocks_library/Delays/finedelay_fstop_prog';'xblocks_library_delays/finedelay_fstop_prog'}, ...
{'xblocks_library/Delays/finedelay_fstop_prog_cordic';'xblocks_library_delays/finedelay_fstop_prog_cordic'}, ...
{'xblocks_library/Delays/partial_delay_prog';'xblocks_library_delays/partial_delay_prog'}, ...
{'xblocks_library/Delays/pipeline';'xblocks_library_delays/pipeline'}, ...
{'xblocks_library/Delays/sync_delay';'xblocks_library_delays/sync_delay'}, ...
{'xblocks_library/Delays/sync_delay_en';'xblocks_library_delays/sync_delay_en'}, ...
{'xblocks_library/Delays/sync_delay_prog';'xblocks_library_delays/sync_delay_prog'}, ...
{'xblocks_library/Delays/window_delay';'xblocks_library_delays/window_delay'}, ...
{'xblocks_library/Downconverter/dds';'xblocks_library_downconverter/dds'}, ...
{'xblocks_library/Downconverter/dec_fir';'xblocks_library_downconverter/dec_fir'}, ...
{'xblocks_library/Downconverter/fir_col';'xblocks_library_downconverter/fir_col'}, ...
{'xblocks_library/Downconverter/fir_dbl_col';'xblocks_library_downconverter/fir_dbl_col'}, ...
{'xblocks_library/Downconverter/fir_dbl_tap';'xblocks_library_downconverter/fir_dbl_tap'}, ...
{'xblocks_library/Downconverter/fir_tap';'xblocks_library_downconverter/fir_tap'}, ...
{'xblocks_library/Downconverter/lo_const';'xblocks_library_downconverter/lo_const'}, ...
{'xblocks_library/Downconverter/lo_osc';'xblocks_library_downconverter/lo_osc'}, ...
{'xblocks_library/Downconverter/mixer';'xblocks_library_downconverter/mixer'}, ...
{'xblocks_library/Downconverter/rcmult';'xblocks_library_downconverter/rcmult'}, ...
{'xblocks_library/Downconverter/sincos';'xblocks_library_downconverter/sincos'}, ...
{'xblocks_library/FFTs/biplex_core';'xblocks_library_ffts/biplex_core'}, ...
{'xblocks_library/FFTs/butterfly_direct';'xblocks_library_ffts/butterfly_direct'}, ...
{'xblocks_library/FFTs/fft';'xblocks_library_ffts/fft'}, ...
{'xblocks_library/FFTs/fft_biplex';'xblocks_library_ffts/fft_biplex'}, ...
{'xblocks_library/FFTs/fft_biplex_real_2x';'xblocks_library_ffts/fft_biplex_real_2x'}, ...
{'xblocks_library/FFTs/fft_biplex_real_4x';'xblocks_library_ffts/fft_biplex_real_4x'}, ...
{'xblocks_library/FFTs/fft_direct';'xblocks_library_ffts/fft_direct'}, ...
{'xblocks_library/FFTs/fft_stage_n';'xblocks_library_ffts/fft_stage_n'}, ...
{'xblocks_library/FFTs/fft_unscrambler';'xblocks_library_ffts/fft_unscrambler'}, ...
{'xblocks_library/FFTs/fft_wideband_real';'xblocks_library_ffts/fft_wideband_real'}, ...
{'xblocks_library/FFTs/Twiddle/twiddle_coeff_0';'xblocks_library_ffts_twiddle/twiddle_coeff_0'}, ...
{'xblocks_library/FFTs/Twiddle/twiddle_coeff_1';'xblocks_library_ffts_twiddle/twiddle_coeff_1'}, ...
{'xblocks_library/FFTs/Twiddle/twiddle_general_3mult';'xblocks_library_ffts_twiddle/twiddle_general_3mult'}, ...
{'xblocks_library/FFTs/Twiddle/twiddle_general_4mult';'xblocks_library_ffts_twiddle/twiddle_general_4mult'}, ...
{'xblocks_library/FFTs/Twiddle/twiddle_pass_through';'xblocks_library_ffts_twiddle/twiddle_pass_through'}, ...
{'xblocks_library/FFTs/Twiddle/twiddle_stage_2';'xblocks_library_ffts_twiddle/twiddle_stage_2'}, ...
{'xblocks_library/FFTs/Twiddle/coeff_gen/coeff_gen';'xblocks_library_ffts_twiddle_coeff_gen/coeff_gen'}, ...
{'xblocks_library/Flow_Control/packetizer';'xblocks_library_flow_control/packetizer'}, ...
{'xblocks_library/Flow_Control/parallel_to_serial_converter';'xblocks_library_flow_control/parallel_to_serial_converter'}, ...
{'xblocks_library/Flow_Control/shifter_unit';'xblocks_library_flow_control/shifter_unit'}, ...
{'xblocks_library/Misc/adc_sim';'xblocks_library_misc/adc_sim'}, ...
{'xblocks_library/Misc/adder_tree';'xblocks_library_misc/adder_tree'}, ...
{'xblocks_library/Misc/armed_trigger';'xblocks_library_misc/armed_trigger'}, ...
{'xblocks_library/Misc/bit_reverse';'xblocks_library_misc/bit_reverse'}, ...
{'xblocks_library/Misc/c_to_ri';'xblocks_library_misc/c_to_ri'}, ...
{'xblocks_library/Misc/complex_addsub';'xblocks_library_misc/complex_addsub'}, ...
{'xblocks_library/Misc/complex_convert';'xblocks_library_misc/complex_convert'}, ...
{'xblocks_library/Misc/conv';'xblocks_library_misc/conv'}, ...
{'xblocks_library/Misc/convert';'xblocks_library_misc/convert'}, ...
{'xblocks_library/Misc/convert_of';'xblocks_library_misc/convert_of'}, ...
{'xblocks_library/Misc/edge';'xblocks_library_misc/edge'}, ...
{'xblocks_library/Misc/edge_detect';'xblocks_library_misc/edge_detect'}, ...
{'xblocks_library/Misc/freeze_cntr';'xblocks_library_misc/freeze_cntr'}, ...
{'xblocks_library/Misc/negedge';'xblocks_library_misc/negedge'}, ...
{'xblocks_library/Misc/negedge_delay';'xblocks_library_misc/negedge_delay'}, ...
{'xblocks_library/Misc/of1';'xblocks_library_misc/of1'}, ...
{'xblocks_library/Misc/posedge';'xblocks_library_misc/posedge'}, ...
{'xblocks_library/Misc/power';'xblocks_library_misc/power'}, ...
{'xblocks_library/Misc/pulse_ext';'xblocks_library_misc/pulse_ext'}, ...
{'xblocks_library/Misc/revision_control';'xblocks_library_misc/revision_control'}, ...
{'xblocks_library/Misc/ri_to_c';'xblocks_library_misc/ri_to_c'}, ...
{'xblocks_library/Misc/sample_and_hold';'xblocks_library_misc/sample_and_hold'}, ...
{'xblocks_library/Misc/stopwatch';'xblocks_library_misc/stopwatch'}, ...
{'xblocks_library/Misc/sync_gen';'xblocks_library_misc/sync_gen'}, ...
{'xblocks_library/Misc/triggered_counter';'xblocks_library_misc/triggered_counter'}, ...
{'xblocks_library/Multipliers/cmult';'xblocks_library_multipliers/cmult'}, ...
{'xblocks_library/Multipliers/cmult_4bit_br';'xblocks_library_multipliers/cmult_4bit_br'}, ...
{'xblocks_library/Multipliers/cmult_4bit_br*';'xblocks_library_multipliers/cmult_4bit_br*'}, ...
{'xblocks_library/Multipliers/cmult_4bit_em';'xblocks_library_multipliers/cmult_4bit_em'}, ...
{'xblocks_library/Multipliers/cmult_4bit_em*';'xblocks_library_multipliers/cmult_4bit_em*'}, ...
{'xblocks_library/Multipliers/cmult_4bit_hdl';'xblocks_library_multipliers/cmult_4bit_hdl'}, ...
{'xblocks_library/Multipliers/cmult_4bit_hdl*';'xblocks_library_multipliers/cmult_4bit_hdl*'}, ...
{'xblocks_library/Multipliers/cmult_4bit_sl';'xblocks_library_multipliers/cmult_4bit_sl'}, ...
{'xblocks_library/Multipliers/cmult_4bit_sl*';'xblocks_library_multipliers/cmult_4bit_sl*'}, ...
{'xblocks_library/PFBs/first_tap';'xblocks_library_pfbs/first_tap'}, ...
{'xblocks_library/PFBs/first_tap_real';'xblocks_library_pfbs/first_tap_real'}, ...
{'xblocks_library/PFBs/last_tap';'xblocks_library_pfbs/last_tap'}, ...
{'xblocks_library/PFBs/last_tap_real';'xblocks_library_pfbs/last_tap_real'}, ...
{'xblocks_library/PFBs/pfb_coeff_gen';'xblocks_library_pfbs/pfb_coeff_gen'}, ...
{'xblocks_library/PFBs/pfb_fir';'xblocks_library_pfbs/pfb_fir'}, ...
{'xblocks_library/PFBs/pfb_fir_real';'xblocks_library_pfbs/pfb_fir_real'}, ...
{'xblocks_library/PFBs/tap';'xblocks_library_pfbs/tap'}, ...
{'xblocks_library/PFBs/tap_real';'xblocks_library_pfbs/tap_real'}, ...
{'xblocks_library/Reorder/barrel_switcher';'xblocks_library_reorder/barrel_switcher'}, ...
{'xblocks_library/Reorder/dbl_buffer';'xblocks_library_reorder/dbl_buffer'}, ...
{'xblocks_library/Reorder/qdr_transpose';'xblocks_library_reorder/qdr_transpose'}, ...
{'xblocks_library/Reorder/reorder';'xblocks_library_reorder/reorder'}, ...
{'xblocks_library/Reorder/square_transposer';'xblocks_library_reorder/square_transposer'}, ...
{'xblocks_library/Scopes/data_capture';'xblocks_library_scopes/data_capture'}, ...
{'xblocks_library/Scopes/dsp_scope';'xblocks_library_scopes/dsp_scope'}, ...
{'xblocks_library/Scopes/sc';'xblocks_library_scopes/sc'}, ...
{'xblocks_library/Scopes/snap';'xblocks_library_scopes/snap'}, ...
{'xblocks_library/Scopes/snap64';'xblocks_library_scopes/snap64'}, ...
{'xblocks_library/Scopes/snap_10gbe_rx';'xblocks_library_scopes/snap_10gbe_rx'}, ...
{'xblocks_library/Scopes/snap_10gbe_tx';'xblocks_library_scopes/snap_10gbe_tx'}, ...
{'xblocks_library/Scopes/snap_32n';'xblocks_library_scopes/snap_32n'}, ...
{'xblocks_library/Scopes/snap_circ';'xblocks_library_scopes/snap_circ'}, ...
{'xblocks_library/Sources/White Gaussian Noise';'xblocks_library_sources/White Gaussian Noise'}, ...
{'xblocks_library/Sources/tt800_uprng';'xblocks_library_sources/tt800_uprng'}, ...
{'xblocks_library/Sources/u2n';'xblocks_library_sources/u2n'}, ...
{'xblocks_library/Filters';'xblocks_library_filters'}, ...
{'xblocks_library/Filters/Internal';'xblocks_library_filters_internal'}, ...
};

end
    